package io.worxbend.gitea4s.model.contract

import zio.json.*

final case class Repository(
    @jsonField("allow_fast_forward_only_merge") allowFastForwardOnlyMerge: Option[Boolean] = None,
    @jsonField("allow_manual_merge") allowManualMerge: Option[Boolean] = None,
    @jsonField("allow_merge_commits") allowMergeCommits: Option[Boolean] = None,
    @jsonField("allow_merge_update") allowMergeUpdate: Option[Boolean] = None,
    @jsonField("allow_rebase") allowRebase: Option[Boolean] = None,
    @jsonField("allow_rebase_explicit") allowRebaseExplicit: Option[Boolean] = None,
    @jsonField("allow_rebase_update") allowRebaseUpdate: Option[Boolean] = None,
    @jsonField("allow_squash_merge") allowSquashMerge: Option[Boolean] = None,
    @jsonField("archived") archived: Option[Boolean] = None,
    @jsonField("archived_at") archivedAt: Option[java.time.Instant] = None,
    @jsonField("autodetect_manual_merge") autodetectManualMerge: Option[Boolean] = None,
    @jsonField("avatar_url") avatarUrl: Option[String] = None,
    @jsonField("branch_count") branchCount: Option[Long] = None,
    @jsonField("clone_url") cloneUrl: Option[String] = None,
    @jsonField("created_at") createdAt: Option[java.time.Instant] = None,
    @jsonField("default_allow_maintainer_edit") defaultAllowMaintainerEdit: Option[Boolean] = None,
    @jsonField("default_branch") defaultBranch: Option[String] = None,
    @jsonField("default_delete_branch_after_merge") defaultDeleteBranchAfterMerge: Option[Boolean] = None,
    @jsonField("default_merge_style") defaultMergeStyle: Option[String] = None,
    @jsonField("default_target_branch") defaultTargetBranch: Option[String] = None,
    @jsonField("default_update_style") defaultUpdateStyle: Option[String] = None,
    @jsonField("description") description: Option[String] = None,
    @jsonField("empty") empty: Option[Boolean] = None,
    @jsonField("external_tracker") externalTracker: Option[ExternalTracker] = None,
    @jsonField("external_wiki") externalWiki: Option[ExternalWiki] = None,
    @jsonField("fork") fork: Option[Boolean] = None,
    @jsonField("forks_count") forksCount: Option[Long] = None,
    @jsonField("full_name") fullName: Option[String] = None,
    @jsonField("has_actions") hasActions: Option[Boolean] = None,
    @jsonField("has_code") hasCode: Option[Boolean] = None,
    @jsonField("has_issues") hasIssues: Option[Boolean] = None,
    @jsonField("has_packages") hasPackages: Option[Boolean] = None,
    @jsonField("has_projects") hasProjects: Option[Boolean] = None,
    @jsonField("has_pull_requests") hasPullRequests: Option[Boolean] = None,
    @jsonField("has_releases") hasReleases: Option[Boolean] = None,
    @jsonField("has_wiki") hasWiki: Option[Boolean] = None,
    @jsonField("html_url") htmlUrl: Option[String] = None,
    @jsonField("id") id: Option[Long] = None,
    @jsonField("ignore_whitespace_conflicts") ignoreWhitespaceConflicts: Option[Boolean] = None,
    @jsonField("internal") internal: Option[Boolean] = None,
    @jsonField("internal_tracker") internalTracker: Option[InternalTracker] = None,
    @jsonField("language") language: Option[String] = None,
    @jsonField("languages_url") languagesUrl: Option[String] = None,
    @jsonField("licenses") licenses: Option[List[String]] = None,
    @jsonField("link") link: Option[String] = None,
    @jsonField("mirror") mirror: Option[Boolean] = None,
    @jsonField("mirror_interval") mirrorInterval: Option[String] = None,
    @jsonField("mirror_last_sync_at") mirrorLastSyncAt: Option[java.time.Instant] = None,
    @jsonField("mirror_updated") mirrorUpdated: Option[java.time.Instant] = None,
    @jsonField("name") name: Option[String] = None,
    @jsonField("object_format_name") objectFormatName: Option[String] = None,
    @jsonField("open_issues_count") openIssuesCount: Option[Long] = None,
    @jsonField("open_pr_counter") openPrCounter: Option[Long] = None,
    @jsonField("original_url") originalUrl: Option[String] = None,
    @jsonField("owner") owner: Option[User] = None,
    @jsonField("parent") parent: Option[Repository] = None,
    @jsonField("permissions") permissions: Option[Permission] = None,
    @jsonField("private") `private`: Option[Boolean] = None,
    @jsonField("projects_mode") projectsMode: Option[String] = None,
    @jsonField("release_counter") releaseCounter: Option[Long] = None,
    @jsonField("repo_transfer") repoTransfer: Option[RepoTransfer] = None,
    @jsonField("size") size: Option[Long] = None,
    @jsonField("ssh_url") sshUrl: Option[String] = None,
    @jsonField("stars_count") starsCount: Option[Long] = None,
    @jsonField("template") template: Option[Boolean] = None,
    @jsonField("topics") topics: Option[List[String]] = None,
    @jsonField("updated_at") updatedAt: Option[java.time.Instant] = None,
    @jsonField("url") url: Option[String] = None,
    @jsonField("watchers_count") watchersCount: Option[Long] = None,
    @jsonField("website") website: Option[String] = None
)

object Repository:
  given JsonCodec[Repository] = DeriveJsonCodec.gen[Repository]
