package io.worxbend.gitea4s.http.contract

object GeneratedAuditExpectations:
  val responseLabels: Map[String, List[(String, String)]] = Map(
    "listAdminWorkflowJobs" -> List(("200", "#/responses/WorkflowJobsList"), ("400", "#/responses/error"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "getAdminRunners" -> List(("200", "#/responses/RunnerList"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "adminCreateRunnerRegistrationToken" -> List(("200", "#/responses/RegistrationToken")),
    "getAdminRunner" -> List(("200", "#/responses/Runner"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "deleteAdminRunner" -> List(("204", "description: runner has been deleted"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "updateAdminRunner" -> List(("200", "#/responses/Runner"), ("400", "#/responses/error"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "listAdminWorkflowRuns" -> List(("200", "#/responses/WorkflowRunsList"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "adminCronList" -> List(("200", "#/responses/CronList"), ("403", "#/responses/forbidden")),
    "adminCronRun" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "adminGetAllEmails" -> List(("200", "#/responses/EmailList"), ("403", "#/responses/forbidden")),
    "adminSearchEmails" -> List(("200", "#/responses/EmailList"), ("403", "#/responses/forbidden")),
    "adminListHooks" -> List(("200", "#/responses/HookList")),
    "adminCreateHook" -> List(("201", "#/responses/Hook")),
    "adminGetHook" -> List(("200", "#/responses/Hook")),
    "adminDeleteHook" -> List(("204", "#/responses/empty")),
    "adminEditHook" -> List(("200", "#/responses/Hook")),
    "adminGetAllOrgs" -> List(("200", "#/responses/OrganizationList"), ("403", "#/responses/forbidden")),
    "adminUnadoptedList" -> List(("200", "#/responses/StringSlice"), ("403", "#/responses/forbidden")),
    "adminAdoptRepository" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "adminDeleteUnadoptedRepository" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden")),
    "adminSearchUsers" -> List(("200", "#/responses/UserList"), ("403", "#/responses/forbidden"), ("422", "#/responses/validationError")),
    "adminCreateUser" -> List(("201", "#/responses/User"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("422", "#/responses/validationError")),
    "adminDeleteUser" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "adminEditUser" -> List(("200", "#/responses/User"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("422", "#/responses/validationError")),
    "adminListUserBadges" -> List(("200", "#/responses/BadgeList"), ("404", "#/responses/notFound")),
    "adminAddUserBadges" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden")),
    "adminDeleteUserBadges" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("422", "#/responses/validationError")),
    "adminCreatePublicKey" -> List(("201", "#/responses/PublicKey"), ("403", "#/responses/forbidden"), ("422", "#/responses/validationError")),
    "adminDeleteUserPublicKey" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "adminCreateOrg" -> List(("201", "#/responses/Organization"), ("403", "#/responses/forbidden"), ("422", "#/responses/validationError")),
    "adminRenameUser" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("422", "#/responses/validationError")),
    "adminCreateRepo" -> List(("201", "#/responses/Repository"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("409", "#/responses/error"), ("422", "#/responses/validationError")),
    "listGitignoresTemplates" -> List(("200", "#/responses/GitignoreTemplateList")),
    "getGitignoreTemplateInfo" -> List(("200", "#/responses/GitignoreTemplateInfo"), ("404", "#/responses/notFound")),
    "listLabelTemplates" -> List(("200", "#/responses/LabelTemplateList")),
    "getLabelTemplateInfo" -> List(("200", "#/responses/LabelTemplateInfo"), ("404", "#/responses/notFound")),
    "listLicenseTemplates" -> List(("200", "#/responses/LicenseTemplateList")),
    "getLicenseTemplateInfo" -> List(("200", "#/responses/LicenseTemplateInfo"), ("404", "#/responses/notFound")),
    "renderMarkdown" -> List(("200", "#/responses/MarkdownRender"), ("422", "#/responses/validationError")),
    "renderMarkdownRaw" -> List(("200", "#/responses/MarkdownRender"), ("422", "#/responses/validationError")),
    "renderMarkup" -> List(("200", "#/responses/MarkupRender"), ("422", "#/responses/validationError")),
    "notifyReadList" -> List(("205", "#/responses/NotificationThreadList")),
    "notifyReadThread" -> List(("205", "#/responses/NotificationThread"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "orgGetAll" -> List(("200", "#/responses/OrganizationList")),
    "orgCreate" -> List(("201", "#/responses/Organization"), ("403", "#/responses/forbidden"), ("422", "#/responses/validationError")),
    "orgDelete" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "orgEdit" -> List(("200", "#/responses/Organization"), ("404", "#/responses/notFound")),
    "getOrgWorkflowJobs" -> List(("200", "#/responses/WorkflowJobsList"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "getOrgRunners" -> List(("200", "#/responses/RunnerList"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "orgCreateRunnerRegistrationToken" -> List(("200", "#/responses/RegistrationToken")),
    "getOrgRunner" -> List(("200", "#/responses/Runner"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "deleteOrgRunner" -> List(("204", "description: runner has been deleted"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "updateOrgRunner" -> List(("200", "#/responses/Runner"), ("400", "#/responses/error"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "getOrgWorkflowRuns" -> List(("200", "#/responses/WorkflowRunsList"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "orgListActionsSecrets" -> List(("200", "#/responses/SecretList"), ("404", "#/responses/notFound")),
    "updateOrgSecret" -> List(("201", "description: response when creating a secret"), ("204", "description: response when updating a secret"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "deleteOrgSecret" -> List(("204", "description: delete one secret of the organization"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "getOrgVariablesList" -> List(("200", "#/responses/VariableList"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "getOrgVariable" -> List(("200", "#/responses/ActionVariable"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "updateOrgVariable" -> List(("201", "description: response when updating an org-level variable"), ("204", "description: response when updating an org-level variable"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "createOrgVariable" -> List(("201", "description: successfully created the org-level variable"), ("400", "#/responses/error"), ("409", "description: variable name already exists."), ("500", "#/responses/error")),
    "deleteOrgVariable" -> List(("200", "#/responses/ActionVariable"), ("201", "description: response when deleting a variable"), ("204", "description: response when deleting a variable"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "orgListActivityFeeds" -> List(("200", "#/responses/ActivityFeedsList"), ("404", "#/responses/notFound")),
    "orgUpdateAvatar" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "orgDeleteAvatar" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "organizationListBlocks" -> List(("200", "#/responses/UserList")),
    "organizationCheckUserBlock" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "organizationBlockUser" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "organizationUnblockUser" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "orgListHooks" -> List(("200", "#/responses/HookList"), ("404", "#/responses/notFound")),
    "orgCreateHook" -> List(("201", "#/responses/Hook"), ("404", "#/responses/notFound")),
    "orgGetHook" -> List(("200", "#/responses/Hook"), ("404", "#/responses/notFound")),
    "orgDeleteHook" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "orgEditHook" -> List(("200", "#/responses/Hook"), ("404", "#/responses/notFound")),
    "orgListLabels" -> List(("200", "#/responses/LabelList"), ("404", "#/responses/notFound")),
    "orgCreateLabel" -> List(("201", "#/responses/Label"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "orgGetLabel" -> List(("200", "#/responses/Label"), ("404", "#/responses/notFound")),
    "orgDeleteLabel" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "orgEditLabel" -> List(("200", "#/responses/Label"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "orgIsMember" -> List(("204", "description: user is a member"), ("303", "description: redirection to /orgs/{org}/public_members/{username}"), ("404", "description: user is not a member")),
    "orgDeleteMember" -> List(("204", "description: member removed"), ("404", "#/responses/notFound")),
    "orgIsPublicMember" -> List(("204", "description: user is a public member"), ("404", "description: user is not a public member")),
    "orgPublicizeMember" -> List(("204", "description: membership publicized"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "orgConcealMember" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "renameOrg" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("422", "#/responses/validationError")),
    "orgListTeams" -> List(("200", "#/responses/TeamList"), ("404", "#/responses/notFound")),
    "orgCreateTeam" -> List(("201", "#/responses/Team"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "teamSearch" -> List(("200", "type:object"), ("404", "#/responses/notFound")),
    "listPackages" -> List(("200", "#/responses/PackageList"), ("404", "#/responses/notFound")),
    "listPackageVersions" -> List(("200", "#/responses/PackageList"), ("404", "#/responses/notFound")),
    "deletePackage" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "getLatestPackageVersion" -> List(("200", "#/responses/Package"), ("404", "#/responses/notFound")),
    "linkPackage" -> List(("201", "#/responses/empty"), ("404", "#/responses/notFound")),
    "unlinkPackage" -> List(("201", "#/responses/empty"), ("404", "#/responses/notFound")),
    "getPackage" -> List(("200", "#/responses/Package"), ("404", "#/responses/notFound")),
    "deletePackageVersion" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "listPackageFiles" -> List(("200", "#/responses/PackageFileList"), ("404", "#/responses/notFound")),
    "issueSearchIssues" -> List(("200", "#/responses/IssueList"), ("400", "#/responses/error"), ("422", "#/responses/validationError")),
    "repoMigrate" -> List(("201", "#/responses/Repository"), ("403", "#/responses/forbidden"), ("409", "description: The repository with the same name already exists."), ("422", "#/responses/validationError")),
    "repoSearch" -> List(("200", "#/responses/SearchResults"), ("422", "#/responses/validationError")),
    "getArtifacts" -> List(("200", "#/responses/ArtifactsList"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "getArtifact" -> List(("200", "#/responses/Artifact"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "deleteArtifact" -> List(("204", "description: No Content"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "listWorkflowJobs" -> List(("200", "#/responses/WorkflowJobsList"), ("400", "#/responses/error"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "getWorkflowJob" -> List(("200", "#/responses/WorkflowJob"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "downloadActionsRunJobLogs" -> List(("200", "description: output blob content"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "getRepoRunners" -> List(("200", "#/responses/RunnerList"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "repoCreateRunnerRegistrationToken" -> List(("200", "#/responses/RegistrationToken")),
    "getRepoRunner" -> List(("200", "#/responses/Runner"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "deleteRepoRunner" -> List(("204", "description: runner has been deleted"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "updateRepoRunner" -> List(("200", "#/responses/Runner"), ("400", "#/responses/error"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "getWorkflowRuns" -> List(("200", "#/responses/WorkflowRunsList"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "GetWorkflowRun" -> List(("200", "#/responses/WorkflowRun"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "deleteActionRun" -> List(("204", "description: No Content"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "getArtifactsOfRun" -> List(("200", "#/responses/ArtifactsList"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "listWorkflowRunJobs" -> List(("200", "#/responses/WorkflowJobsList"), ("400", "#/responses/error"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "rerunWorkflowJob" -> List(("201", "#/responses/WorkflowJob"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("409", "#/responses/error"), ("422", "#/responses/validationError")),
    "rerunWorkflowRun" -> List(("201", "#/responses/WorkflowRun"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("409", "#/responses/error"), ("422", "#/responses/validationError")),
    "rerunFailedWorkflowRun" -> List(("201", "#/responses/empty"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("409", "#/responses/error"), ("422", "#/responses/validationError")),
    "repoListActionsSecrets" -> List(("200", "#/responses/SecretList"), ("404", "#/responses/notFound")),
    "updateRepoSecret" -> List(("201", "description: response when creating a secret"), ("204", "description: response when updating a secret"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "deleteRepoSecret" -> List(("204", "description: delete one secret of the repository"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "ListActionTasks" -> List(("200", "#/responses/TasksList"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("409", "#/responses/conflict"), ("422", "#/responses/validationError")),
    "getRepoVariablesList" -> List(("200", "#/responses/VariableList"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "getRepoVariable" -> List(("200", "#/responses/ActionVariable"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "updateRepoVariable" -> List(("201", "description: response when updating a repo-level variable"), ("204", "description: response when updating a repo-level variable"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "createRepoVariable" -> List(("201", "description: response when creating a repo-level variable"), ("400", "#/responses/error"), ("409", "description: variable name already exists."), ("500", "#/responses/error")),
    "deleteRepoVariable" -> List(("200", "#/responses/ActionVariable"), ("201", "description: response when deleting a variable"), ("204", "description: response when deleting a variable"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "ActionsListRepositoryWorkflows" -> List(("200", "#/responses/ActionWorkflowList"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError"), ("500", "#/responses/error")),
    "ActionsGetWorkflow" -> List(("200", "#/responses/ActionWorkflow"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError"), ("500", "#/responses/error")),
    "ActionsDisableWorkflow" -> List(("204", "description: No Content"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "ActionsDispatchWorkflow" -> List(("200", "#/responses/RunDetails"), ("204", "description: No Content, if return_run_details is missing or false"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "ActionsEnableWorkflow" -> List(("204", "description: No Content"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("409", "#/responses/conflict"), ("422", "#/responses/validationError")),
    "repoListActivityFeeds" -> List(("200", "#/responses/ActivityFeedsList"), ("404", "#/responses/notFound")),
    "repoUpdateAvatar" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "repoDeleteAvatar" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "repoAddCollaborator" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "repoDeleteCollaborator" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "repoGetAllCommits" -> List(("200", "#/responses/CommitList"), ("404", "#/responses/notFound"), ("409", "#/responses/EmptyRepository")),
    "repoCompareDiff" -> List(("200", "#/responses/Compare"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "repoChangeFiles" -> List(("201", "#/responses/FilesResponse"), ("403", "#/responses/error"), ("404", "#/responses/notFound"), ("422", "#/responses/error"), ("423", "#/responses/repoArchivedError")),
    "repoGetContentsExt" -> List(("200", "#/responses/ContentsExtResponse"), ("404", "#/responses/notFound")),
    "repoUpdateFile" -> List(("200", "#/responses/FileResponse"), ("201", "#/responses/FileResponse"), ("403", "#/responses/error"), ("404", "#/responses/notFound"), ("422", "#/responses/error"), ("423", "#/responses/repoArchivedError")),
    "repoCreateFile" -> List(("201", "#/responses/FileResponse"), ("403", "#/responses/error"), ("404", "#/responses/notFound"), ("422", "#/responses/error"), ("423", "#/responses/repoArchivedError")),
    "repoDeleteFile" -> List(("200", "#/responses/FileDeleteResponse"), ("400", "#/responses/error"), ("403", "#/responses/error"), ("404", "#/responses/error"), ("422", "#/responses/error"), ("423", "#/responses/repoArchivedError")),
    "repoApplyDiffPatch" -> List(("200", "#/responses/FileResponse"), ("404", "#/responses/notFound"), ("423", "#/responses/repoArchivedError")),
    "repoGetEditorConfig" -> List(("200", "description: success"), ("404", "#/responses/notFound")),
    "repoGetFileContents" -> List(("200", "#/responses/ContentsListResponse"), ("404", "#/responses/notFound")),
    "repoGetFileContentsPost" -> List(("200", "#/responses/ContentsListResponse"), ("404", "#/responses/notFound")),
    "listForks" -> List(("200", "#/responses/RepositoryList"), ("404", "#/responses/notFound")),
    "repoListHooks" -> List(("200", "#/responses/HookList"), ("404", "#/responses/notFound")),
    "repoCreateHook" -> List(("201", "#/responses/Hook"), ("404", "#/responses/notFound")),
    "repoGetHook" -> List(("200", "#/responses/Hook"), ("404", "#/responses/notFound")),
    "repoDeleteHook" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "repoEditHook" -> List(("200", "#/responses/Hook"), ("404", "#/responses/notFound")),
    "repoTestHook" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "repoGetIssueConfig" -> List(("200", "#/responses/RepoIssueConfig"), ("404", "#/responses/notFound")),
    "repoValidateIssueConfig" -> List(("200", "#/responses/RepoIssueConfigValidation"), ("404", "#/responses/notFound")),
    "repoGetIssueTemplates" -> List(("200", "#/responses/IssueTemplates"), ("404", "#/responses/notFound")),
    "issueListIssueCommentAttachments" -> List(("200", "#/responses/AttachmentList"), ("404", "#/responses/error")),
    "issueGetIssueCommentAttachment" -> List(("200", "#/responses/Attachment"), ("404", "#/responses/error")),
    "issueDeleteIssueCommentAttachment" -> List(("204", "#/responses/empty"), ("404", "#/responses/error"), ("423", "#/responses/repoArchivedError")),
    "issueEditIssueCommentAttachment" -> List(("201", "#/responses/Attachment"), ("404", "#/responses/error"), ("422", "#/responses/validationError"), ("423", "#/responses/repoArchivedError")),
    "issueListIssueAttachments" -> List(("200", "#/responses/AttachmentList"), ("404", "#/responses/error")),
    "issueGetIssueAttachment" -> List(("200", "#/responses/Attachment"), ("404", "#/responses/error")),
    "issueDeleteIssueAttachment" -> List(("204", "#/responses/empty"), ("404", "#/responses/error"), ("423", "#/responses/repoArchivedError")),
    "issueEditIssueAttachment" -> List(("201", "#/responses/Attachment"), ("404", "#/responses/error"), ("422", "#/responses/validationError"), ("423", "#/responses/repoArchivedError")),
    "issueDeleteCommentDeprecated" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "issueEditCommentDeprecated" -> List(("200", "#/responses/Comment"), ("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "issueGetCommentsAndTimeline" -> List(("200", "#/responses/TimelineList"), ("404", "#/responses/notFound")),
    "repoListKeys" -> List(("200", "#/responses/DeployKeyList"), ("404", "#/responses/notFound")),
    "repoCreateKey" -> List(("201", "#/responses/DeployKey"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "repoGetKey" -> List(("200", "#/responses/DeployKey"), ("404", "#/responses/notFound")),
    "repoDeleteKey" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "issueListLabels" -> List(("200", "#/responses/LabelList"), ("404", "#/responses/notFound")),
    "issueCreateLabel" -> List(("201", "#/responses/Label"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "issueGetLabel" -> List(("200", "#/responses/Label"), ("404", "#/responses/notFound")),
    "issueDeleteLabel" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "issueEditLabel" -> List(("200", "#/responses/Label"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "repoGetLicenses" -> List(("200", "#/responses/LicensesList"), ("404", "#/responses/notFound")),
    "repoMergeUpstream" -> List(("200", "#/responses/MergeUpstreamResponse"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "issueGetMilestonesList" -> List(("200", "#/responses/MilestoneList"), ("404", "#/responses/notFound")),
    "issueCreateMilestone" -> List(("201", "#/responses/Milestone"), ("404", "#/responses/notFound")),
    "issueGetMilestone" -> List(("200", "#/responses/Milestone"), ("404", "#/responses/notFound")),
    "issueDeleteMilestone" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "issueEditMilestone" -> List(("200", "#/responses/Milestone"), ("404", "#/responses/notFound")),
    "repoMirrorSync" -> List(("200", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "notifyGetRepoList" -> List(("200", "#/responses/NotificationThreadList")),
    "notifyReadRepoList" -> List(("205", "#/responses/NotificationThreadList")),
    "repoListPushMirrors" -> List(("200", "#/responses/PushMirrorList"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "repoAddPushMirror" -> List(("200", "#/responses/PushMirror"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "repoPushMirrorSync" -> List(("200", "#/responses/empty"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "repoGetPushMirrorByRemoteName" -> List(("200", "#/responses/PushMirror"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "repoDeletePushMirror" -> List(("204", "#/responses/empty"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "repoCreateRelease" -> List(("201", "#/responses/Release"), ("404", "#/responses/notFound"), ("409", "#/responses/error"), ("422", "#/responses/validationError")),
    "repoDeleteReleaseByTag" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "repoDeleteRelease" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "repoEditRelease" -> List(("200", "#/responses/Release"), ("404", "#/responses/notFound")),
    "repoDeleteReleaseAttachment" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "repoEditReleaseAttachment" -> List(("201", "#/responses/Attachment"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "repoSigningKeySSH" -> List(("200", "type:string")),
    "userCurrentCheckSubscription" -> List(("200", "#/responses/WatchInfo"), ("404", "description: User is not watching this repo or repo do not exist")),
    "userCurrentPutSubscription" -> List(("200", "#/responses/WatchInfo"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "userCurrentDeleteSubscription" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "repoCreateTag" -> List(("200", "#/responses/Tag"), ("404", "#/responses/notFound"), ("405", "#/responses/empty"), ("409", "#/responses/conflict"), ("422", "#/responses/validationError"), ("423", "#/responses/repoArchivedError")),
    "repoDeleteTag" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound"), ("405", "#/responses/empty"), ("409", "#/responses/conflict"), ("422", "#/responses/validationError"), ("423", "#/responses/repoArchivedError")),
    "repoAddTeam" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("405", "#/responses/error"), ("422", "#/responses/validationError")),
    "repoDeleteTeam" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("405", "#/responses/error"), ("422", "#/responses/validationError")),
    "repoTrackedTimes" -> List(("200", "#/responses/TrackedTimeList"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "userTrackedTimes" -> List(("200", "#/responses/TrackedTimeList"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "repoUpdateTopics" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound"), ("422", "#/responses/invalidTopicsError")),
    "repoAddTopic" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound"), ("422", "#/responses/invalidTopicsError")),
    "repoDeleteTopic" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound"), ("422", "#/responses/invalidTopicsError")),
    "repoCreateWikiPage" -> List(("201", "#/responses/WikiPage"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("423", "#/responses/repoArchivedError")),
    "repoGetWikiPage" -> List(("200", "#/responses/WikiPage"), ("404", "#/responses/notFound")),
    "repoDeleteWikiPage" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("423", "#/responses/repoArchivedError")),
    "repoEditWikiPage" -> List(("200", "#/responses/WikiPage"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("423", "#/responses/repoArchivedError")),
    "repoGetWikiPages" -> List(("200", "#/responses/WikiPageList"), ("404", "#/responses/notFound")),
    "repoGetWikiPageRevisions" -> List(("200", "#/responses/WikiCommitList"), ("404", "#/responses/notFound")),
    "generateRepo" -> List(("201", "#/responses/Repository"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("409", "description: The repository with the same name already exists."), ("422", "#/responses/validationError")),
    "repoGetByID" -> List(("200", "#/responses/Repository"), ("404", "#/responses/notFound")),
    "getSigningKey" -> List(("200", "type:string")),
    "getSigningKeySSH" -> List(("200", "type:string")),
    "orgGetTeam" -> List(("200", "#/responses/Team"), ("404", "#/responses/notFound")),
    "orgDeleteTeam" -> List(("204", "description: team deleted"), ("404", "#/responses/notFound")),
    "orgEditTeam" -> List(("200", "#/responses/Team"), ("404", "#/responses/notFound")),
    "orgListTeamActivityFeeds" -> List(("200", "#/responses/ActivityFeedsList"), ("404", "#/responses/notFound")),
    "orgListTeamMembers" -> List(("200", "#/responses/UserList"), ("404", "#/responses/notFound")),
    "orgListTeamMember" -> List(("200", "#/responses/User"), ("404", "#/responses/notFound")),
    "orgAddTeamMember" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "orgRemoveTeamMember" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "orgListTeamRepos" -> List(("200", "#/responses/RepositoryList"), ("404", "#/responses/notFound")),
    "orgListTeamRepo" -> List(("200", "#/responses/Repository"), ("404", "#/responses/notFound")),
    "orgAddTeamRepository" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "orgRemoveTeamRepository" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "topicSearch" -> List(("200", "#/responses/TopicListResponse"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "getUserWorkflowJobs" -> List(("200", "#/responses/WorkflowJobsList"), ("400", "#/responses/error"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "getUserRunners" -> List(("200", "#/responses/RunnerList"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "userCreateRunnerRegistrationToken" -> List(("200", "#/responses/RegistrationToken")),
    "getUserRunner" -> List(("200", "#/responses/Runner"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "deleteUserRunner" -> List(("204", "description: runner has been deleted"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "updateUserRunner" -> List(("200", "#/responses/Runner"), ("400", "#/responses/error"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "getUserWorkflowRuns" -> List(("200", "#/responses/WorkflowRunsList"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "updateUserSecret" -> List(("201", "description: response when creating a secret"), ("204", "description: response when updating a secret"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "deleteUserSecret" -> List(("204", "description: delete one secret of the user"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "getUserVariablesList" -> List(("200", "#/responses/VariableList"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "getUserVariable" -> List(("200", "#/responses/ActionVariable"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "updateUserVariable" -> List(("201", "description: response when updating a variable"), ("204", "description: response when updating a variable"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "createUserVariable" -> List(("201", "description: successfully created the user-level variable"), ("400", "#/responses/error"), ("409", "description: variable name already exists.")),
    "deleteUserVariable" -> List(("201", "description: response when deleting a variable"), ("204", "description: response when deleting a variable"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "userGetOauth2Application" -> List(("200", "#/responses/OAuth2ApplicationList")),
    "userCreateOAuth2Application" -> List(("201", "#/responses/OAuth2Application"), ("400", "#/responses/error")),
    "userGetOAuth2Application" -> List(("200", "#/responses/OAuth2Application"), ("404", "#/responses/notFound")),
    "userDeleteOAuth2Application" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "userUpdateOAuth2Application" -> List(("200", "#/responses/OAuth2Application"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "userUpdateAvatar" -> List(("204", "#/responses/empty")),
    "userDeleteAvatar" -> List(("204", "#/responses/empty")),
    "userListBlocks" -> List(("200", "#/responses/UserList")),
    "userCheckUserBlock" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "userBlockUser" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "userUnblockUser" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "userListEmails" -> List(("200", "#/responses/EmailList")),
    "userAddEmail" -> List(("201", "#/responses/EmailList"), ("422", "#/responses/validationError")),
    "userDeleteEmail" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "userCurrentListFollowers" -> List(("200", "#/responses/UserList")),
    "userCurrentListFollowing" -> List(("200", "#/responses/UserList")),
    "userCurrentCheckFollowing" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "userCurrentPutFollow" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "userCurrentDeleteFollow" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "getVerificationToken" -> List(("200", "#/responses/string"), ("404", "#/responses/notFound")),
    "userVerifyGPGKey" -> List(("201", "#/responses/GPGKey"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "userCurrentListGPGKeys" -> List(("200", "#/responses/GPGKeyList")),
    "userCurrentPostGPGKey" -> List(("201", "#/responses/GPGKey"), ("404", "#/responses/notFound"), ("422", "#/responses/validationError")),
    "userCurrentGetGPGKey" -> List(("200", "#/responses/GPGKey"), ("404", "#/responses/notFound")),
    "userCurrentDeleteGPGKey" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "userListHooks" -> List(("200", "#/responses/HookList")),
    "userCreateHook" -> List(("201", "#/responses/Hook")),
    "userGetHook" -> List(("200", "#/responses/Hook")),
    "userDeleteHook" -> List(("204", "#/responses/empty")),
    "userEditHook" -> List(("200", "#/responses/Hook")),
    "userCurrentListKeys" -> List(("200", "#/responses/PublicKeyList")),
    "userCurrentPostKey" -> List(("201", "#/responses/PublicKey"), ("422", "#/responses/validationError")),
    "userCurrentGetKey" -> List(("200", "#/responses/PublicKey"), ("404", "#/responses/notFound")),
    "userCurrentDeleteKey" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "orgListCurrentUserOrgs" -> List(("200", "#/responses/OrganizationList"), ("404", "#/responses/notFound")),
    "userCurrentListRepos" -> List(("200", "#/responses/RepositoryList")),
    "getUserSettings" -> List(("200", "#/responses/UserSettings")),
    "updateUserSettings" -> List(("200", "#/responses/UserSettings")),
    "userCurrentListStarred" -> List(("200", "#/responses/RepositoryList"), ("403", "#/responses/forbidden")),
    "userCurrentCheckStarring" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "userCurrentPutStar" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "userCurrentDeleteStar" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "userCurrentListSubscriptions" -> List(("200", "#/responses/RepositoryList")),
    "userListTeams" -> List(("200", "#/responses/TeamList")),
    "userCurrentTrackedTimes" -> List(("200", "#/responses/TrackedTimeList")),
    "userListActivityFeeds" -> List(("200", "#/responses/ActivityFeedsList"), ("404", "#/responses/notFound")),
    "userCheckFollowing" -> List(("204", "#/responses/empty"), ("404", "#/responses/notFound")),
    "userListGPGKeys" -> List(("200", "#/responses/GPGKeyList"), ("404", "#/responses/notFound")),
    "userGetHeatmapData" -> List(("200", "#/responses/UserHeatmapData"), ("404", "#/responses/notFound")),
    "userListKeys" -> List(("200", "#/responses/PublicKeyList"), ("404", "#/responses/notFound")),
    "orgListUserOrgs" -> List(("200", "#/responses/OrganizationList"), ("404", "#/responses/notFound")),
    "orgGetUserPermissions" -> List(("200", "#/responses/OrganizationPermissions"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "userListStarred" -> List(("200", "#/responses/RepositoryList"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound")),
    "userListSubscriptions" -> List(("200", "#/responses/RepositoryList"), ("404", "#/responses/notFound")),
    "userGetTokens" -> List(("200", "#/responses/AccessTokenList"), ("403", "#/responses/forbidden")),
    "userCreateToken" -> List(("201", "#/responses/AccessToken"), ("400", "#/responses/error"), ("403", "#/responses/forbidden")),
    "userDeleteAccessToken" -> List(("204", "#/responses/empty"), ("403", "#/responses/forbidden"), ("404", "#/responses/notFound"), ("422", "#/responses/error")),
    "getVersion" -> List(("200", "#/responses/ServerVersion")),
    "downloadArtifact" -> List(("302", "description: redirect to the blob download"), ("400", "#/responses/error"), ("404", "#/responses/notFound")),
    "issueCreateIssueCommentAttachment" -> List(("201", "#/responses/Attachment"), ("400", "#/responses/error"), ("403", "#/responses/forbidden"), ("404", "#/responses/error"), ("413", "#/responses/error"), ("422", "#/responses/validationError"), ("423", "#/responses/repoArchivedError")),
    "issueCreateIssueAttachment" -> List(("201", "#/responses/Attachment"), ("400", "#/responses/error"), ("404", "#/responses/error"), ("413", "#/responses/error"), ("422", "#/responses/validationError"), ("423", "#/responses/repoArchivedError")),
    "repoCreateReleaseAttachment" -> List(("201", "#/responses/Attachment"), ("400", "#/responses/error"), ("404", "#/responses/notFound"), ("413", "#/responses/error"))
  )
